name: GitHub to Telegram Notification

on:
  push:
    branches:
      - main  # á¬áŠá¶á€áŸ‹áˆáŸ’á˜áŸ„áŸ‡ branch áŠáŸ‚á›á¢áŸ’á“á€á”áŸ’ášá¾ (á§á‘á¶á ášááŸ: master, dev)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>ğŸš€ New Commit in Flutter Project</b>

            <b>Repo:</b> ${{ github.repository }}
            <b>Branch:</b> <code>${{ github.ref_name }}</code>
            <b>Author:</b> ${{ github.actor }}

            <b>Message:</b>
            <i>${{ github.event.commits[0].message }}</i>

            <a href="${{ github.event.commits[0].url }}">View Commit on GitHub</a>
